###########___________Testing UTF8 for HEROKU
POST https://homefin-server.herokuapp.com/categories
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name":"Дом","capacity":10000,"userId":1}


###########___________Testing UTF8
POST http://localhost:8080/categories
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name":"Дом","capacity":10000}



###########___________EmailExists
GET http://localhost:8080/auth/emailExists?email=andrew@gmail.com
Accept: */*
Cache-Control: no-cache
###########___________UsernameExists
GET http://localhost:8080/auth/usernameExists?username=AndrewUser
Accept: */*
Cache-Control: no-cache
###########___________CurrencyTest2
GET https://api.exchangeratesapi.io/latest
Accept: */*
Cache-Control: no-cache

##############___________CurrencyTest
GET http://data.fixer.io/api/latest?access_key=045c429915bce5ab8772387f75420c28
Accept: */*
Cache-Control: no-cache
###

###########___________AuthJwt
POST http://localhost:8080/auth/signup
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name":"Michael", "username":"Mich","email":"michael@gmail.com","password":"dasdqwe"}
###
POST http://localhost:8080/auth/signup
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name":"Alia", "username":"AliaUser","email":"alia@gmail.com","password":"dasdqwe"}
###

POST http://localhost:8080/auth/signin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"username":"AndrewUser", "password":"dasdqwe"}
###

POST http://localhost:8080/auth/signin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"username":"AliaUser", "password":"dasdqwe"}
###
POST http://localhost:8080/auth/signin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"username":"Mich", "password":"dasdqwe"}
###


###########___________User
GET http://localhost:8080/users
Accept: */*
Cache-Control: no-cache
###
GET http://localhost:8080/users?email=andrew@gmail.com
Accept: */*
Cache-Control: no-cache
###

GET http://localhost:8080/users/2
Accept: application/json
Cache-Control: no-cache
###
POST http://localhost:8080/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name":"Michael","email":10000,"password":"michael@gmail.com"}
###
PUT http://localhost:8080/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"id":1, "name":"MichaelPut","email":10000,"password":"michaelPut@gmail.com"}
###
DELETE http://localhost:8080/users/3
Accept: application/json
Cache-Control: no-cache
###

###########___________Bill
GET http://localhost:8080/bill
Accept: */*
Cache-Control: no-cache
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTM4NjI2MjQ5LCJleHAiOjE1MzkyMzEwNDl9.AucBOBbk73yX_hNk7tvb-aB0_C_xnhr_JH_UI_niqpdGKx326dGwhLHx7eX-7TKphFWGROI_0XQkx7tS6bF9sg
###

GET http://localhost:8080/bill/2
Accept: application/json
Cache-Control: no-cache
###
POST http://localhost:8080/bill
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"value":15000,"currency":"RUB"}
###
PUT http://localhost:8080/bill
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


{"id":1,"value":85000,"currency":"$"}
###
DELETE http://localhost:8080/bill/1
Accept: application/json
Cache-Control: no-cache
###

###########___________Category
GET http://localhost:8080/categories
Accept: */*
Cache-Control: no-cache
###

GET http://localhost:8080/categories/2
Accept: application/json
Cache-Control: no-cache
###
POST http://localhost:8080/categories
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name":"Home","capacity":10000}
###
PUT http://localhost:8080/categories
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"id":1,"name":"Car","capacity":4000}
###
DELETE http://localhost:8080/categories/3
Accept: application/json
Cache-Control: no-cache
###

###########___________Event
GET http://localhost:8080/events
Accept: */*
Cache-Control: no-cache
###

GET http://localhost:8080/events/2
Accept: application/json
Cache-Control: no-cache
###
POST http://localhost:8080/events
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"type":"outc","amount":1500.00,"category":1,"date":"12.08.2017", "description":"Car"}
###
PUT http://localhost:8080/events
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"id":5,"type":"put","amount":3210.00,"category":3,"date":"12.08.2017","description":"CarPut"}
###
DELETE http://localhost:8080/events/4
Accept: application/json
Cache-Control: no-cache
###



###########___________PERSON

GET http://localhost:8080/person
Accept: application/json
Cache-Control: no-cache
###
GET http://localhost:8080/person/1
Accept: application/json
Cache-Control: no-cache
###
POST http://localhost:8080/person
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{"id":3,"firstname":"Arslan","lastname":"Ovezov"}
###
PUT http://localhost:8080/person
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{"id":1,"firstname":"Arslan","lastname":"Ovezov"}
###
DELETE http://localhost:8080/person/3
Accept: application/json
Cache-Control: no-cache
###
